language: node_js
node_js:
  - 12
dist: trusty
env:
  – NODE_ENV=production
cache:
  directories:
    – node_modules
install:
  – npm install
  – npm install --dev
  – npm run build
script:
  – npm run build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: tomochan-code-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: tomochandv/inventory #Github 주소
      branch: master