language: node_js
node_js:
  - 12
dist: trusty
env:
  – NODE_ENV=production
cache:
  directories:
    – node_modules
install:
  – npm install
  – npm install --dev
  – npm run build
script:
  – npm run build

before_deploy:
  - zip -r nodejsdist *
  - mkdir -p deploy
  - mv nodejsdist.zip deploy/nodejsdist.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: tomochan-code-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    wait-until-deployed: true
    local_dir: deploy
    on:
      repo: tomochandv/inventory #Github 주소
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: ap-northeast-2
    bucket: tomochan-code-deploy
    key: nodejsdist.zip # S3 버킷에 저장된 파일을 EC2로 배포
    bundle_type: zip
    application: inventory # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: inventory-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    wait-until-deployed: true
    on:
      repo: tomochandv/inventory #Github 주소
      branch: master
    
    
    
